<Gerenciador>:
    Menu:
        name: 'menu'
    
    Tarefas:
        name: 'tarefas'

    Vendas:
        name: 'vendas'
        
    Finalizar:
        name: 'finalizar'
  


<Menu>
    BoxLayout:
        
        orientation: 'vertical'
        padding:  20
        spacing: 20
        Image: 
            source: 'logo.png'
        
        BoxLayout:
            
            orientation: 'vertical'
            spacing: 10
            padding: 30
            Button: 
                text: 'Vender'
                on_press: root.iniciar_dia()
                on_release: app.root.current = 'vendas'
            Button:
                text: 'Gerar Relatório do dia'
                on_release: root.gerar_relatorio()
            Button: 
                text: 'Enviar relatório por email'
                on_release: root.email()
            Button: 
                text: 'Fechar dia'
                on_release: root.fechar_dia()
            


<Vendas>:

    BoxLayout:
        orientation:'vertical'
        padding: 20
        spacing: 10
        BoxLayout:
            orientation: 'vertical'
            size_hint_y : None
            height: root.height/15
            Label:
                
                text: 'O que deseja vender?'
        
        BoxLayout:
            BoxLayout:
                padding: 10
                spacing: 10
                orientation: 'vertical'
                
                
                Button:
                    text: 'tekla' 
                    
                    on_release: root.add_peca(0)
                Button:
                    text: 'Nery'
                    on_release: root.add_peca(1)
                Button:
                    text: 'hanger'
                    on_release: root.add_peca(2)
                Button:
                    text: 'hanger duplo'
                    on_release: root.add_peca(3)
                Button:
                    text: 'hanger rede'
                    on_release: root.add_peca(4)
                Button:
                    text: 'hanger triplo'
                    on_release: root.add_peca(5)
                Button:
                    text: 'hanger triplo mini'
                    on_release: root.add_peca(6)
            
                
            BoxLayout:
                padding: 10
                spacing: 10
                orientation:'vertical'
                Button:
                    text: 'segura cortina'
                    on_release: root.add_peca(7)
                Button:
                    text: 'cinto'
                    on_release: root.add_peca(8)
                Button:
                    text: 'almofada'
                    on_release: root.add_peca(9)
                Button:
                    text: 'lampada'
                    on_release: root.add_peca(10)
                Button:
                    text: 'mão francesa'
                    on_release: root.add_peca(11)
                Button:
                    text: 'mini painel'
                    on_release: root.add_peca(12)
                Button:
                    text: 'bolacha de madeira'
                    on_release: root.add_peca(13)
        
        
       
        
        BoxLayout:
            
            spacing: 5
            orientation: 'vertical'
            size_hint_y : None
            height: root.height/10
            Label: 
                text: 'Outras vendas:     '       
            BoxLayout:
                size_hint_y : None
                height: root.height/10
                TextInput:
                    id: outros_lancamentos
               
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: None
                    width: root.width * 1/7
                    spacing: 5
                    Button:
                        text: '+'
                        on_release: root.outros_valores('+')
                    Button:
                        text: '-'
                        on_release: root.outros_valores('-')
                    
        BoxLayout:
            
        
            orientation: 'vertical'
            size_hint_y : None
            height: root.height/15
            BoxLayout:
                size_hint_y : None
                height: root.height/20
                Label:
                    id: 'status'
                    text: ' '
                Button:
                    text: 'voltar'
                    size_hint_x: None     
                    width: root.width * 1/10
                    on_release: app.root.current = 'menu'
    
<Finalizar>
    BoxLayout:
        orientation: 'vertical'
        padding:  100
        spacing: 50
        Image: 
            source: 'logo.png'
        Button:
            text: 'Gerar Relatório do dia'
            on_release: app.root.current = app.stop()
        Button: 
            text: 'Enviar relatório por email'
            on_release: "None"
        Button: 
            text: 'Fechar dia'
            on_release: root.fechar_dia()
        Button:
            text: 'voltar'
            size_hint_x: None     
            width: root.width * 1/10
            on_release: app.root.current = 'menu'
    

















    
    
    
<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:60
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:60
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:200
    Label:
        id:label
        font_size:30
    Button:
        text:'X'
        size_hint_x:None
        width:60
        on_release:app.root.get_screen('tarefas').ids.box.remove_widget(root)